package com.test.springboot.v2.demo.dao.mybatis.vo;

import java.util.Date;


public class ArenaInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arena_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arena_info.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arena_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arena_info.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arena_info.arena_describe
     *
     * @mbg.generated
     */
    private String arenaDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arena_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arena_info.id
     *
     * @return the value of arena_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arena_info.id
     *
     * @param id the value for arena_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arena_info.uid
     *
     * @return the value of arena_info.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arena_info.uid
     *
     * @param uid the value for arena_info.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arena_info.status
     *
     * @return the value of arena_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arena_info.status
     *
     * @param status the value for arena_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arena_info.title
     *
     * @return the value of arena_info.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arena_info.title
     *
     * @param title the value for arena_info.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arena_info.arena_describe
     *
     * @return the value of arena_info.arena_describe
     *
     * @mbg.generated
     */
    public String getArenaDescribe() {
        return arenaDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arena_info.arena_describe
     *
     * @param arenaDescribe the value for arena_info.arena_describe
     *
     * @mbg.generated
     */
    public void setArenaDescribe(String arenaDescribe) {
        this.arenaDescribe = arenaDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arena_info.create_time
     *
     * @return the value of arena_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arena_info.create_time
     *
     * @param createTime the value for arena_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
