package com.test.springboot.v2.demo.dao.mybatis.vo;

import java.util.Date;


public class CodeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.code
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.used
     *
     * @mbg.generated
     */
    private Boolean used;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.phone
     *
     * @return the value of code_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.phone
     *
     * @param phone the value for code_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.create_date
     *
     * @return the value of code_info.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.create_date
     *
     * @param createDate the value for code_info.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.code
     *
     * @return the value of code_info.code
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.code
     *
     * @param code the value for code_info.code
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.used
     *
     * @return the value of code_info.used
     *
     * @mbg.generated
     */
    public Boolean getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.used
     *
     * @param used the value for code_info.used
     *
     * @mbg.generated
     */
    public void setUsed(Boolean used) {
        this.used = used;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
