package com.test.springboot.v2.demo.dao.mybatis.vo;

import java.util.Date;


public class VoteInfo extends VoteInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_info.last_udate_time
     *
     * @mbg.generated
     */
    private Date lastUdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_info.create_time
     *
     * @return the value of vote_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_info.create_time
     *
     * @param createTime the value for vote_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_info.last_udate_time
     *
     * @return the value of vote_info.last_udate_time
     *
     * @mbg.generated
     */
    public Date getLastUdateTime() {
        return lastUdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_info.last_udate_time
     *
     * @param lastUdateTime the value for vote_info.last_udate_time
     *
     * @mbg.generated
     */
    public void setLastUdateTime(Date lastUdateTime) {
        this.lastUdateTime = lastUdateTime;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
