package com.test.springboot.v2.demo.dao.mybatis.vo;


public class VoteInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_info.arena_id
     *
     * @mbg.generated
     */
    private Long arenaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_info.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_info.arena_id
     *
     * @return the value of vote_info.arena_id
     *
     * @mbg.generated
     */
    public Long getArenaId() {
        return arenaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_info.arena_id
     *
     * @param arenaId the value for vote_info.arena_id
     *
     * @mbg.generated
     */
    public void setArenaId(Long arenaId) {
        this.arenaId = arenaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_info.uid
     *
     * @return the value of vote_info.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_info.uid
     *
     * @param uid the value for vote_info.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
