package com.test.springboot.v2.demo.dao.mybatis.mapper;

import com.test.springboot.v2.demo.dao.mybatis.vo.ArenaInfo;
import com.test.springboot.v2.demo.dao.mybatis.vo.ArenaInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface ArenaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    long countByExample(ArenaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int deleteByExample(ArenaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int insert(ArenaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int insertSelective(ArenaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    List<ArenaInfo> selectByExample(ArenaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    ArenaInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArenaInfo record, @Param("example") ArenaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArenaInfo record, @Param("example") ArenaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArenaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arena_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArenaInfo record);


	       ////*******自定义开始********/
        //***********自定义结束****////
}
