server:
  port: 8080
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #监控统计拦截的filters
      filters: stat
      #基本属性
      url: jdbc:mysql://193.112.46.75:3306/thinker?characterEncoding=utf-8
      username: root
      password: 123456

      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  # mapper-locations: classpath:com/test/springboot/v2/demo/dao/mybatis/mapper/*.xml
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.test.springboot.v2.demo.dao.mybatis.vo

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 打印sql
logging:
  level:
    com.test.springboot.v2.demo.dao.mybatis.mapper: debug
